name: qrorder
description: Customer QR Ordering App - Technical Test
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8

  #di
  get_it: ^9.2.1

  # Networking
  dio: ^5.9.2

  # QR Scanner
  mobile_scanner: ^7.2.0

  # UI / Fonts
  google_fonts: ^8.1.0

  # Utils
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  dartz: any
  flutter_dotenv: ^6.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  l10n_gen: ^1.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.5
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - .env